version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
       POSTGRES_USER= postgres
       POSTGRES_DB = review
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  hello-world:
    image: hello-world
    ports:
      - "8080:8080"